---
title: "Secondary Analysis"
author: "Christian Wollmann"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: true
    toc_depth: 2
    theme: united
---
# =========================================
# 1 Specifying Models
# =========================================

## 1.1 Creating df_secondary for secondary analysis
df_secondary <- read.csv("df_long.csv")

# val_cat direkt faktorisieren (geordnet: neg < neu < pos)
df_secondary$val_cat <- factor(df_secondary$val_cat, levels = c("neg", "neu", "pos"))

# gr direkt faktorisieren (exp = 0, sham = 1)
df_secondary$gr <- factor(df_secondary$gr, levels = c("20Hz_online_exp", "20Hz_online_sham"))

## 1.2 Specification of Models
s1 <- lmer(val ~ gr * val_cat + (1|subj), data = df_secondary)
s2 <- lmer(val ~ gr * val_cat + age + sex + (1|subj), data = df_secondary)
s3 <- lmer(val ~ gr * val_cat + age + sex + rMT + (1|subj), data = df_secondary)


# =========================================
# 1.3 Plotting Dependent Variable (DV)
# =========================================

## Figure for val (Secondary DV)
v <- ggplot(df_secondary, aes(x = val_cat, y = val, fill = gr)) +
  stat_summary(fun = mean, geom = "bar", 
               position = position_dodge(width = 1), 
               alpha = 0.5, color = "black") +
  stat_summary(fun.data = mean_cl_normal, 
               geom = "errorbar", 
               position = position_dodge(width = 1), 
               width = 0.2, color = "black") +
  scale_fill_manual(values = c("20Hz_online_exp" = "#0072B2",
                               "20Hz_online_sham" = "#D55E00"),
                    labels = c("experimental", "control"),
                    name = "Group") +
  scale_x_discrete(labels = c("neg" = "negative", 
                              "neu" = "neutral", 
                              "pos" = "positive")) +
  labs(x = "", y = "", fill = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
v

# =========================================
# 2 Verifying Assumptions
# =========================================

# =========================================
# 2.1 Univariate Outliers
# =========================================

## Visualization of Univariate Outliers
g2 <- ggplot(df_secondary, aes(x = "", y = val)) +  
  stat_boxplot(geom = "errorbar", width = 0.6, color = "black", alpha = 0.5, lwd = 0.3) +
  geom_boxplot(fill = "grey", color = "black", alpha = 0.5, lwd = 0.3, outlier.size = 2, outlier.shape = 8) +  
  geom_jitter(aes(color = gr), width = 0.3, height = 0, alpha = 0.8) +  
  scale_color_manual(
    values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00"),
    labels = c("experimental", "control"),
    name = "Group"
  ) +
  scale_y_continuous(limits = c(-200, 200)) +
  labs(x = NULL, y = NULL, title = NULL) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 10, hjust = 0.5),
    legend.text = element_text(size = 9),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.line = element_line(color = "black", linewidth = 0.5)
  )
g2

## Quantification of Univariate Outliers
Q1_val <- quantile(df_secondary$val, 0.25, na.rm = TRUE)
Q3_val <- quantile(df_secondary$val, 0.75, na.rm = TRUE)
IQR_val <- IQR(df_secondary$val, na.rm = TRUE)

lower_bound_val <- Q1_val - 1.5 * IQR_val
upper_bound_val <- Q3_val + 1.5 * IQR_val

outliers_val <- df_secondary %>%
  filter(val < lower_bound_val | val > upper_bound_val)

outliers_val


# =========================================
# 2.2 Multivariate Outliers (Cook's Distance)
# =========================================

## Quantification of Cook's Distance
inf_s1 <- influence(s1, obs = TRUE)
inf_s2 <- influence(s2, obs = TRUE)
inf_s3 <- influence(s3, obs = TRUE)

cd_s1 <- cooks.distance(inf_s1)
cd_s2 <- cooks.distance(inf_s2)
cd_s3 <- cooks.distance(inf_s3)

## Influential Cases
critical_threshold <- 1
conservative_threshold <- 4 / nrow(df_secondary)

analyze_cooks_distance <- function(cd, model_name) {
  critical_points <- which(cd > critical_threshold)
  conservative_points <- which(cd > conservative_threshold)
  
  cat(paste("\n--- Cook's Distance Analysis for", model_name, "---\n"))
  
  if (length(critical_points) > 0) {
    cat("Indizes (CD > 1):\n")
    print(critical_points)
  } else {
    cat("Keine Punkte mit CD > 1 gefunden.\n")
  }
  
  if (length(conservative_points) > 0) {
    cat("Indizes (CD > 4/N):\n")
    print(conservative_points)
  } else {
    cat("Keine Punkte mit CD > 4/N gefunden.\n")
  }
}

analyze_cooks_distance(cd_s1, "s1")
analyze_cooks_distance(cd_s2, "s2")
analyze_cooks_distance(cd_s3, "s3")

## Mapping between index and subject
cd4n_s1 <- c(6, 36, 45)
cd4n_s2 <- c(4, 6, 36, 40, 45)
cd4n_s3 <- c(4, 6, 36, 45, 63)

subj_cd4n_s1 <- df_secondary$subj[cd4n_s1]
subj_cd4n_s2 <- df_secondary$subj[cd4n_s2]
subj_cd4n_s3 <- df_secondary$subj[cd4n_s3]

cat("\n--- Cook's Distance > 4/N: s1 ---\n")
cat("subj IDs:", subj_cd4n_s1, "\n")

cat("\n--- Cook's Distance > 4/N: s2 ---\n")
cat("subj IDs:", subj_cd4n_s2, "\n")

cat("\n--- Cook's Distance > 4/N: s3 ---\n")
cat("subj IDs:", subj_cd4n_s3, "\n")

## Visualization of Cook's Distance
y_threshold_sec <- 4 / nrow(df_secondary)
y_limit_sec <- range(c(cd_s1, cd_s2, cd_s3, y_threshold_sec), na.rm = TRUE)

par(mfrow = c(1, 3), mai = c(0.5, 0.6, 0.3, 0.25), oma = c(3, 0, 0, 0))

# PLOT 1: s1
plot(cd_s1, type = "h", main = "", ylab = "", xlab = "", ylim = y_limit_sec, cex.lab = 1.2, col = "black")
abline(h = 1, col = "#0072B2", lty = 2)
abline(h = y_threshold_sec, col = "#CC79A7", lty = 2)
segments(x0 = cd4n_s1, y0 = 0, x1 = cd4n_s1, y1 = cd_s1[cd4n_s1], col = "red", lwd = 1)

# PLOT 2: s2
plot(cd_s2, type = "h", main = "", ylab = "", xlab = "", ylim = y_limit_sec, cex.lab = 1.2, col = "black")
abline(h = 1, col = "#0072B2", lty = 2)
abline(h = y_threshold_sec, col = "#CC79A7", lty = 2)
segments(x0 = cd4n_s2, y0 = 0, x1 = cd4n_s2, y1 = cd_s2[cd4n_s2], col = "red", lwd = 1)

# PLOT 3: s3
plot(cd_s3, type = "h", main = "", ylab = "", xlab = "", ylim = y_limit_sec, cex.lab = 1.2, col = "black")
abline(h = 1, col = "#0072B2", lty = 2)
abline(h = y_threshold_sec, col = "#CC79A7", lty = 2)
segments(x0 = cd4n_s3, y0 = 0, x1 = cd4n_s3, y1 = cd_s3[cd4n_s3], col = "red", lwd = 1)

mtext("Observation Index", side = 1, line = 1.5, outer = TRUE, cex = par("cex.lab"))
par(mfrow = c(1, 1))

# =========================================
# 2.3 Multicollinearity
# =========================================

## Checking Variance Inflation Factors (VIF)

check_collinearity(s1)
check_collinearity(s2)
check_collinearity(s3)


# =========================================
# 2.4 Normal Distribution of Errors
# =========================================

## Calculation of Standardized Residuals

# Compute raw residuals
df_secondary$resid_s1 <- resid(s1)
df_secondary$resid_s2 <- resid(s2)
df_secondary$resid_s3 <- resid(s3)

# Compute standardized residuals
df_secondary$stand_resid_s1 <- scale(df_secondary$resid_s1)[, 1]
df_secondary$stand_resid_s2 <- scale(df_secondary$resid_s2)[, 1]
df_secondary$stand_resid_s3 <- scale(df_secondary$resid_s3)[, 1]


## Preparing Kernel Density Estimation (KDE) and Normal Distributions

# s1
s1_density <- data.frame(
  x = density(df_secondary$stand_resid_s1)$x,
  y = density(df_secondary$stand_resid_s1)$y,
  type = "Empirical Density"
)
s1_normal <- data.frame(
  x = seq(min(df_secondary$stand_resid_s1), max(df_secondary$stand_resid_s1), length.out = 100),
  y = dnorm(seq(min(df_secondary$stand_resid_s1), max(df_secondary$stand_resid_s1), length.out = 100)),
  type = "Normal Distribution"
)

# s2
s2_density <- data.frame(
  x = density(df_secondary$stand_resid_s2)$x,
  y = density(df_secondary$stand_resid_s2)$y,
  type = "Empirical Density"
)
s2_normal <- data.frame(
  x = seq(min(df_secondary$stand_resid_s2), max(df_secondary$stand_resid_s2), length.out = 100),
  y = dnorm(seq(min(df_secondary$stand_resid_s2), max(df_secondary$stand_resid_s2), length.out = 100)),
  type = "Normal Distribution"
)

# s3
s3_density <- data.frame(
  x = density(df_secondary$stand_resid_s3)$x,
  y = density(df_secondary$stand_resid_s3)$y,
  type = "Empirical Density"
)
s3_normal <- data.frame(
  x = seq(min(df_secondary$stand_resid_s3), max(df_secondary$stand_resid_s3), length.out = 100),
  y = dnorm(seq(min(df_secondary$stand_resid_s3), max(df_secondary$stand_resid_s3), length.out = 100)),
  type = "Normal Distribution"
)


# =========================================
# 2.4.1 Model S1: Normality Check
# =========================================

## S1: Histogram
s1_lines <- rbind(s1_density, s1_normal)

s1_hist <- ggplot(df_secondary, aes(x = stand_resid_s1)) +
  geom_histogram(aes(y = ..density..), fill = "grey", color = "black", binwidth = 0.25) +
  geom_line(data = s1_lines, aes(x = x, y = y, color = type), linewidth = 1) +
  scale_color_manual(name = "Line Type", values = c("Empirical Density" = "#CC79A7", "Normal Distribution" = "#F0E442")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s1_hist

## S1: QQ-Plot
df_secondary$theoretical_quantiles_s1 <- qqnorm(df_secondary$stand_resid_s1, plot.it = FALSE)$x

s1_qq <- ggplot(df_secondary, aes(x = theoretical_quantiles_s1, y = stand_resid_s1, color = gr)) +
  geom_jitter(width = 0.3, height = 0, size = 1.5, alpha = 0.7) +
  geom_abline(intercept = mean(df_secondary$stand_resid_s1), slope = sd(df_secondary$stand_resid_s1), color = "#CC79A7", linewidth = 1) +
  scale_color_manual(values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s1_qq

## S1: Normality Tests
shapiro_residuals_s1 <- shapiro.test(df_secondary$resid_s1)
ad_residuals_s1 <- ad.test(df_secondary$resid_s1)

cat("\n#---------------------------------------#\n")
cat("## Model s1 - Normality Tests\n")
cat("\nShapiro-Wilk Test:\n")
print(shapiro_residuals_s1)
cat("\nAnderson-Darling Test:\n")
print(ad_residuals_s1)


# =========================================
# 2.4.2 Model S2: Normality Check
# =========================================

## S2: Histogram
s2_lines <- rbind(s2_density, s2_normal)

s2_hist <- ggplot(df_secondary, aes(x = stand_resid_s2)) +
  geom_histogram(aes(y = ..density..), fill = "grey", color = "black", binwidth = 0.25) +
  geom_line(data = s2_lines, aes(x = x, y = y, color = type), linewidth = 1) +
  scale_color_manual(name = "Line Type", values = c("Empirical Density" = "#CC79A7", "Normal Distribution" = "#F0E442")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s2_hist

## S2: QQ-Plot
df_secondary$theoretical_quantiles_s2 <- qqnorm(df_secondary$stand_resid_s2, plot.it = FALSE)$x

s2_qq <- ggplot(df_secondary, aes(x = theoretical_quantiles_s2, y = stand_resid_s2, color = gr)) +
  geom_jitter(width = 0.3, height = 0, size = 1.5, alpha = 0.7) +
  geom_abline(intercept = mean(df_secondary$stand_resid_s2), slope = sd(df_secondary$stand_resid_s2), color = "#CC79A7", linewidth = 1) +
  scale_color_manual(values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s2_qq

## S2: Normality Tests
shapiro_residuals_s2 <- shapiro.test(df_secondary$resid_s2)
ad_residuals_s2 <- ad.test(df_secondary$resid_s2)

cat("\n#---------------------------------------#\n")
cat("## Model s2 - Normality Tests\n")
cat("\nShapiro-Wilk Test:\n")
print(shapiro_residuals_s2)
cat("\nAnderson-Darling Test:\n")
print(ad_residuals_s2)


# =========================================
# 2.4.3 Model S3: Normality Check
# =========================================

## S3: Histogram
s3_lines <- rbind(s3_density, s3_normal)

s3_hist <- ggplot(df_secondary, aes(x = stand_resid_s3)) +
  geom_histogram(aes(y = ..density..), fill = "grey", color = "black", binwidth = 0.25) +
  geom_line(data = s3_lines, aes(x = x, y = y, color = type), linewidth = 1) +
  scale_color_manual(name = "Line Type", values = c("Empirical Density" = "#CC79A7", "Normal Distribution" = "#F0E442")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s3_hist

## S3: QQ-Plot
df_secondary$theoretical_quantiles_s3 <- qqnorm(df_secondary$stand_resid_s3, plot.it = FALSE)$x

s3_qq <- ggplot(df_secondary, aes(x = theoretical_quantiles_s3, y = stand_resid_s3, color = gr)) +
  geom_jitter(width = 0.3, height = 0, size = 1.5, alpha = 0.7) +
  geom_abline(intercept = mean(df_secondary$stand_resid_s3), slope = sd(df_secondary$stand_resid_s3), color = "#CC79A7", linewidth = 1) +
  scale_color_manual(values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00")) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s3_qq

## S3: Normality Tests
shapiro_residuals_s3 <- shapiro.test(df_secondary$resid_s3)
ad_residuals_s3 <- ad.test(df_secondary$resid_s3)

cat("\n#---------------------------------------#\n")
cat("## Model s3 - Normality Tests\n")
cat("\nShapiro-Wilk Test:\n")
print(shapiro_residuals_s3)
cat("\nAnderson-Darling Test:\n")
print(ad_residuals_s3)

# =========================================
# 2.5 Variance Homogeneity
# =========================================

## 2.5.1 Visualization for Model S1

# Fitted Values and Residuals
df_secondary$fitted_s1 <- fitted(s1)

# Global linear fit (optional, not used in plot)
global_fit_s1 <- lm(resid(s1) ~ fitted(s1))

# Adding jitter to fitted values for visualization
set.seed(123)
df_secondary$fitted_jit_s1 <- df_secondary$fitted_s1 + runif(nrow(df_secondary), -8, 8)

# Creating intervals
df_secondary$interval_s1 <- cut(
  df_secondary$fitted_s1,
  breaks = c(-200, -70, -30, 30, 70, 180),
  include.lowest = TRUE,
  right = FALSE
)

# Plot for model s1
s1_var <- ggplot(df_secondary, aes(x = fitted_jit_s1, y = stand_resid_s1, color = gr)) +
  geom_segment(aes(x = fitted_jit_s1, xend = fitted_jit_s1, y = stand_resid_s1, yend = 0),
               color = "#009E73", linewidth = 0.1, alpha = 0.7) +
  geom_point(alpha = 0.8, size = 1.5) +
  geom_hline(aes(yintercept = 0, linetype = "No Deviation"), color = "black") +
  facet_wrap(~interval_s1, scales = "free_x") +
  scale_color_manual(
    values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00"),
    labels = c("Experimental", "Sham"),
    name = "Group"
  ) +
  scale_linetype_manual(
    values = c("No Deviation" = "solid"),
    name = "Linetype"
  ) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s1_var


## 2.5.2 Visualization for Model S2

# Fitted Values
df_secondary$fitted_s2 <- fitted(s2)
global_fit_s2 <- lm(resid(s2) ~ fitted(s2))

# Jitter
set.seed(123)
df_secondary$fitted_jit_s2 <- df_secondary$fitted_s2 + runif(nrow(df_secondary), -8, 8)

# Intervals
df_secondary$interval_s2 <- cut(
  df_secondary$fitted_s2,
  breaks = c(-200, -70, -30, 30, 70, 180),
  include.lowest = TRUE,
  right = FALSE
)

# Plot for model s2
s2_var <- ggplot(df_secondary, aes(x = fitted_jit_s2, y = stand_resid_s2, color = gr)) +
  geom_segment(aes(x = fitted_jit_s2, xend = fitted_jit_s2, y = stand_resid_s2, yend = 0),
               color = "#009E73", linewidth = 0.1, alpha = 0.7) +
  geom_point(alpha = 0.8, size = 1.5) +
  geom_hline(aes(yintercept = 0, linetype = "No Deviation"), color = "black") +
  facet_wrap(~interval_s2, scales = "free_x") +
  scale_color_manual(
    values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00"),
    labels = c("Experimental", "Sham"),
    name = "Group"
  ) +
  scale_linetype_manual(
    values = c("No Deviation" = "solid"),
    name = "Linetype"
  ) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s2_var


## 2.5.3 Visualization for Model S3

# Fitted Values
df_secondary$fitted_s3 <- fitted(s3)
global_fit_s3 <- lm(resid(s3) ~ fitted(s3))

# Jitter
set.seed(123)
df_secondary$fitted_jit_s3 <- df_secondary$fitted_s3 + runif(nrow(df_secondary), -8, 8)

# Intervals
df_secondary$interval_s3 <- cut(
  df_secondary$fitted_s3,
  breaks = c(-200, -70, -30, 30, 70, 180),
  include.lowest = TRUE,
  right = FALSE
)

# Plot for model s3
s3_var <- ggplot(df_secondary, aes(x = fitted_jit_s3, y = stand_resid_s3, color = gr)) +
  geom_segment(aes(x = fitted_jit_s3, xend = fitted_jit_s3, y = stand_resid_s3, yend = 0),
               color = "#009E73", linewidth = 0.1, alpha = 0.7) +
  geom_point(alpha = 0.8, size = 1.5) +
  geom_hline(aes(yintercept = 0, linetype = "No Deviation"), color = "black") +
  facet_wrap(~interval_s3, scales = "free_x") +
  scale_color_manual(
    values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00"),
    labels = c("Experimental", "Sham"),
    name = "Group"
  ) +
  scale_linetype_manual(
    values = c("No Deviation" = "solid"),
    name = "Linetype"
  ) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(legend.title = element_text(hjust = 0.5))
s3_var


## 2.5.4 Quantification of Variance Homogeneity

# Breusch-Pagan-type tests
bp_s1 <- check_heteroscedasticity(s1)
bp_s2 <- check_heteroscedasticity(s2)
bp_s3 <- check_heteroscedasticity(s3)

# Output
print(bp_s1)
print(bp_s2)
print(bp_s3)


# =========================================
# 3 Inferential Analysis
# =========================================

# 3.1 Model Fit Comparison: AIC and BIC

model_list_sec <- list(s1, s2, s3)
model_names_sec <- c("S1", "S2", "S3")

model_comparison_sec <- data.frame(
  Model = model_names_sec,
  AIC = sapply(model_list_sec, AIC),
  BIC = sapply(model_list_sec, BIC)
)

print(model_comparison_sec)

# =========================================
# 3.2 Model Results
# =========================================

## 3.2.1 Results S1

# Modell S1 schätzen
s1 <- lmer(val ~ gr * val_cat + (1|subj), data = df_secondary)

# Klassische Auswertung
summary(s1)
model_parameters(s1, ci = 0.95)

# Robuste Inferenz für Modell S1
inference_s1_with_ci <- compute_cr2_ci(s1, df_secondary$subj)

# Ausgabe robuste Schätzungen für S1
library(knitr)
kable(inference_s1_with_ci, caption = "Robust inference with 95% confidence intervals – Model S1")

# Effektgrößen mit Bootstrapping
boot_r2_function <- function(model) {
  r2beta(model, method = "nsj")$Rsq
}

set.seed(123)
boot_s1_results <- bootMer(s1, FUN = boot_r2_function, nsim = 1000, use.u = TRUE, type = "parametric")

boot_r2_means_s1 <- apply(boot_s1_results$t, 2, mean)
boot_r2_cis_s1 <- apply(boot_s1_results$t, 2, quantile, probs = c(0.025, 0.975))

boot_s1_summary <- data.frame(
  Effect = r2beta(s1, method = "nsj")$Effect,
  Boot_R2 = round(boot_r2_means_s1, 4),
  CI_Lower = round(boot_r2_cis_s1[1, ], 4),
  CI_Upper = round(boot_r2_cis_s1[2, ], 4)
)

print(boot_s1_summary)


## 3.2.2 Results S2

# Modell S2 schätzen
s2 <- lmer(val ~ gr * val_cat + age + sex + (1|subj), data = df_secondary)

# Klassische Auswertung
summary(s2)
model_parameters(s2, ci = 0.95)

# Robuste Inferenz für Modell S2
inference_s2_with_ci <- compute_cr2_ci(s2, df_secondary$subj)

# Ausgabe robuste Schätzungen für S2
kable(inference_s2_with_ci, caption = "Robust inference with 95% confidence intervals – Model S2")

# Effektgrößen mit Bootstrapping
set.seed(123)
boot_s2_results <- bootMer(s2, FUN = boot_r2_function, nsim = 1000, use.u = TRUE, type = "parametric")

boot_r2_means_s2 <- apply(boot_s2_results$t, 2, mean)
boot_r2_cis_s2 <- apply(boot_s2_results$t, 2, quantile, probs = c(0.025, 0.975))

boot_s2_summary <- data.frame(
  Effect = r2beta(s2, method = "nsj")$Effect,
  Boot_R2 = round(boot_r2_means_s2, 4),
  CI_Lower = round(boot_r2_cis_s2[1, ], 4),
  CI_Upper = round(boot_r2_cis_s2[2, ], 4)
)

print(boot_s2_summary)

# Plotting: robustes Interaction Plot für S2
vcov_s2_cr2 <- vcovCR(s2, cluster = df_secondary$subj, type = "CR2")

emm_s2_robust <- emmeans(s2, ~ gr * val_cat, vcov. = vcov_s2_cr2)
emm_df_s2_robust <- as.data.frame(emm_s2_robust)

plot_s2_robust <- ggplot(emm_df_s2_robust, aes(x = val_cat, y = emmean, color = gr, group = gr)) +
  geom_line(linewidth = 1, position = position_dodge(0.3)) +
  geom_point(size = 3, position = position_dodge(0.3)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    width = 0.15,
    position = position_dodge(0.3)
  ) +
  scale_x_discrete(labels = c("neg" = "Negative", "neu" = "Neutral", "pos" = "Positive")) +
  scale_color_manual(
    values = c("20Hz_online_exp" = "#0072B2", "20Hz_online_sham" = "#D55E00"),
    labels = c("experimental", "control"),
    name = "Group"
  ) +
  labs(title = "", x = "", y = "") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 11),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )

# Plot anzeigen
print(plot_s2_robust)


## 3.2.3 Results S3

# Modell S3 schätzen
s3 <- lmer(val ~ gr * val_cat + age + sex + rMT + (1|subj), data = df_secondary)

# Klassische Auswertung
summary(s3)
model_parameters(s3, ci = 0.95)

# Robuste Inferenz für Modell S3
inference_s3_with_ci <- compute_cr2_ci(s3, df_secondary$subj)

# Ausgabe robuste Schätzungen für S3
kable(inference_s3_with_ci, caption = "Robust inference with 95% confidence intervals – Model S3")

# Effektgrößen mit Bootstrapping
set.seed(123)
boot_s3_results <- bootMer(s3, FUN = boot_r2_function, nsim = 1000, use.u = TRUE, type = "parametric")

boot_r2_means_s3 <- apply(boot_s3_results$t, 2, mean)
boot_r2_cis_s3 <- apply(boot_s3_results$t, 2, quantile, probs = c(0.025, 0.975))

boot_s3_summary <- data.frame(
  Effect = r2beta(s3, method = "nsj")$Effect,
  Boot_R2 = round(boot_r2_means_s3, 4),
  CI_Lower = round(boot_r2_cis_s3[1, ], 4),
  CI_Upper = round(boot_r2_cis_s3[2, ], 4)
)

print(boot_s3_summary)
